# Generated by Django 5.2 on 2025-04-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('telegram_id', models.CharField(primary_key=True, serialize=False)),
                ('if_below', models.IntegerField()),
            ],
        ),
    ]
