# Generated by Django 5.2 on 2025-04-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signals',
            new_name='Signal',
        ),
    ]
