# Generated by Django 5.2 on 2025-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='real',
            field=models.FloatField(null=True),
        ),
    ]
